---
- import_tasks: preflight.yml

- import_tasks: install.yml
  become: true

- import_tasks: configure.yml
  become: true

- name: Ensure prometheus_msteams is enabled on boot
  become: true
  systemd:
    daemon_reload: true
    name: prometheus_msteams
    enabled: true
    state: started
