---
- name: Assert usage of systemd as an init system
  assert:
    that: ansible_service_mgr == 'systemd'
    msg: "This role only works with systemd"

- name: Get systemd version
  command: systemctl --version
  changed_when: false
  check_mode: false
  register: __systemd_version
  tags:
    - skip_ansible_lint

- name: Set systemd version fact
  set_fact:
    prometheus_msteams_systemd_version: "{{ __systemd_version.stdout_lines[0] | regex_replace('^systemd\\s(\\d+).*$', '\\1') }}"

- block:
    - name: Get checksum list from github
      set_fact:
        _checksums: "{{ lookup('url', 'https://github.com/prometheus-msteams/prometheus-msteams/releases/download/v' + prometheus_msteams_version + '/shasum256.txt', wantlist=True) | list }}"
      run_once: true
    - name: "Get checksum for linux-amd64 architecture"
      set_fact:
        prometheus_msteams_checksum: "{{ item.split(' ')[0] }}"
      with_items: "{{ _checksums }}"
      when:
        - "('prometheus-msteams-linux-amd64') in item"
  delegate_to: localhost
  when: prometheus_msteams_binary_local_dir | length == 0