name: build

on: [push, pull_request]

jobs:
  ansible-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Lint Ansible Playbook
      uses: ansible/ansible-lint-action@master
      with:
       targets: |
        */*.yml

  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install system dependencies
        run: |
          sudo apt-get update \
          && sudo apt-get install -y libvirt-dev
      - name: Install a default Python
        uses: actions/setup-python@v2
        # workaround to avoid getting 3.9 in:
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install --no-cache-dir -r requirements.txt
      - name: Molecule test
        run: |
             molecule --debug test
