name: molecule-test

on: [push, pull_request]

jobs:
  molecule:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install system dependencies
        run: |
          sudo apt-get update \
          && sudo apt-get install -y libvirt-dev
      - name: Install a default Python
        uses: actions/setup-python@v2
        # workaround to avoid getting 3.9 in:
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install --no-cache-dir molecule
          pip install --no-cache-dir molecule[docker,lint]
          pip install molecule-inspec
      - name: Molecule test
        run: |
             pwd
             ls
             molecule --debug test
